docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['Saha_test']
    Saha_test:
      plugin: 'opennav_docking::SimpleChargingDock'  # Also 'opennav_docking::SimpleNonChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    #dock_database: /home/tayya/Nav2_Dock_Robot/src/auto_dock/params/dock_database.yaml

    docks: ['test_dock','test_dock2']
    test_dock:
      type: 'Saha_test'
      frame: map
      pose: [1.0, 2.0, 0.0]
      id: 'c67f50cb-e152-4720-85cc-5eb20bd85ce8'
    
    test_dock2:
      type: 'Saha_test'
      frame: map
      pose: [1.0, 3.0, 0.0]
      id: 'c67y00cb-c367-4380-897vv-5eb15gd85ce8'

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15